### ISSUE TITLE
Issue: GPU is not used with Ctransformers even after specifying gpu_layers parameter

### ISSUE THREAD

**Issue by YogeshTembe** [langchain-ai/langchain#11826]
### Issue you'd like to raise.

I have installed langchain and ctransformer using -

```
pip install langchain
pip install ctransformers[cuda]
```

I am trying following piece of code -

```
from langchain.llms import CTransformers
config = {'max_new_tokens': 512, 'repetition_penalty': 1.1, 'context_length': 8000, 'temperature':0, 'gpu_layers':50}
llm = CTransformers(model = "./codellama-7b.Q4_0.gguf", model_type = "llama", gpu_layers=50, config=config)
```

Here gpu_layers parameter is specified still gpu is not being used and complete load is on cpu.
Can someone please point out if there is any step missing.

**Comment by YogeshTembe** [comment]
@dosu-bot I am trying to use "Ctransformers" library from langchain and you are referring to "HuggingFacePipeline" library.

Can you please suggest some way to use gpu with  "Ctransformers" library in langchain

**Comment by YogeshTembe** [comment]
Yes sure. Here is the required information - 
1) langchain version = 0.0.306 , ctransformers version = 0.2.27
2) CUDA version = 12.2
3) There is no error or warning. Just that this code uses cpu and not gpu
4) I am not setting which gpu device to use naywhere because I could not find any ctransformers parameter to do so.

**Comment by YogeshTembe** [comment]
@dosu-bot The solution provided does not work. Also Accelarate is not part of langchain as well.

`from langchain.llms import Accelerate`

does not work.

**Comment by iamsach** [comment]
The accelerate fix worked for me. And now the models are loaded in the GPU, after I passed in the LLM that I have instantiated with CTransformers to the prepare method of Accelerator class

**Comment by Jeevi10** [comment]
I tried all of this and still my volatile memory is zero. @lamsach, Can you please provide some Details about how did you manage to get it run ?

**Comment by iamsach** [comment]
I used this @Jeevi10

 `from accelerate import Accelerator
from langchain.llms import CTransformers

accelerator = Accelerator()

config = {'max_new_tokens': 512, 'repetition_penalty': 1.1, 'context_length': 8000, 'temperature':0, 'gpu_layers':50}
llm = CTransformers(model = "./codellama-7b.Q4_0.gguf", model_type = "llama", gpu_layers=50, config=config)

llm, config = accelerator.prepare(llm, config)`

It was running in the GPU after that and I got results pretty fast.

**Comment by christopher11** [comment]
> _🤖_
> 
> Hello,
> 
> Thank you for reaching out. It seems like you're trying to use the GPU with the CTransformers library in LangChain, but it's not working as expected.
> 
> From the context provided, it appears that there was a similar issue reported in the LangChain repository ([Issue #648](https://github.com/langchain-ai/langchain/issues/648)). The suggested solution was to install the 'accelerate' module from HuggingFace. However, you mentioned that you've already tried this and it didn't work.
> 
> The 'accelerate' module is not a part of LangChain, which is why the import `from langchain.llms import Accelerate` is not working. The 'accelerate' module is a separate library that needs to be installed and imported separately.
> 
> Here's how you can do it:
> 
> 1. Install the 'accelerate' library using pip:
> 
> ```shell
> pip install accelerate
> ```
> 
> 2. Import the 'accelerate' library in your code:
> 
> ```python
> from accelerate import Accelerator
> ```
> 
> 3. Use the 'accelerator' object to prepare your model and optimizer:
> 
> ```python
> accelerator = Accelerator()
> model, optimizer = accelerator.prepare(model, optimizer)
> ```
> 
> Please note that you need to replace 'model' and 'optimizer' with your actual model and optimizer.
> 
> If you're still facing issues, could you please provide more details about the error messages you're getting? This will help me understand the problem better and provide a more accurate solution.
> 
> Best regards.
> 
> ## Sources
> * [Missing GPU support? HuggingFace model too slow](https://github.com/langchain-ai/langchain/issues/648)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

This worked me as well!

**Comment by VIGHNESH1521** [comment]
from langchain.llms import CTransformers
from dotenv import find_dotenv, load_dotenv
import box
import yaml
from accelerate import Accelerator
from ctransformers import AutoModelForCausalLM

# Load environment variables from .env file
load_dotenv(find_dotenv())

# Import config vars
with open('config/config.yml', 'r', encoding='utf8') as ymlfile:
    cfg = box.Box(yaml.safe_load(ymlfile))

accelerator = Accelerator()
def build_llm():
    # # Local CTransformers model
    # llm = CTransformers(model=cfg.MODEL_BIN_PATH,
    #                     model_type=cfg.MODEL_TYPE,
    #                     config={'max_new_tokens': cfg.MAX_NEW_TOKENS,
    #                             'temperature': cfg.TEMPERATURE,
    #                              'gpu_layers': 50}
    #                     )
    
    config = {'max_new_tokens': 256, 'repetition_penalty': 1.1, 'context_length': 8000, 'temperature':0.01, 'gpu_layers':50}
    llm = AutoModelForCausalLM.from_pretrained('TheBloke/Llama-2-7B-Chat-GGML',model_file='llama-2-7b-chat.ggmlv3.q8_0.bin',model_type="llama", **config)
    
    llm, config = accelerator.prepare(llm, config)

    return llm

I have this code, but my agenda is the model should be able to utilize the GPU, it should not run on CPU, are there any changes to be made in the code?

**Comment by Kev703in** [comment]
try adding this:

     llm = CTransformers(model=cfg.MODEL_BIN_PATH,
                        model_type=cfg.MODEL_TYPE,
                        config={'max_new_tokens': cfg.MAX_NEW_TOKENS,
                                'temperature': cfg.TEMPERATURE,
                                 'gpu_layers': 50}
                        )
    **llm = accelerator.prepare(llm)**

    return llm
    
    I just use:
    config = {'max_new_tokens': cfg.MAX_NEW_TOKENS,
                                'temperature': cfg.TEMPERATURE,
                                 'gpu_layers': 50}
    llm = CTransformers(model=cfg.MODEL_BIN_PATH,
                        model_type=cfg.MODEL_TYPE,
                        config= config
                        )
    llm,config = accelerator.prepare(llm,config)
    return llm

**Comment by VIGHNESH1521** [comment]
> @VIGHNESH1521 
> try adding this:
> 
>      llm = CTransformers(model=cfg.MODEL_BIN_PATH,
>                         model_type=cfg.MODEL_TYPE,
>                         config={'max_new_tokens': cfg.MAX_NEW_TOKENS,
>                                 'temperature': cfg.TEMPERATURE,
>                                  'gpu_layers': 50}
>                         )
>     **llm = accelerator.prepare(llm)**
> 
>     return llm
>     
>     I just use:
>     config = {'max_new_tokens': cfg.MAX_NEW_TOKENS,
>                                 'temperature': cfg.TEMPERATURE,
>                                  'gpu_layers': 50}
>     llm = CTransformers(model=cfg.MODEL_BIN_PATH,
>                         model_type=cfg.MODEL_TYPE,
>                         config= config
>                         )
>     llm,config = accelerator.prepare(llm,config)
>     return llm
>     

@Kev703in I had tried this before posting here, it is not working....

**Comment by saadjelbini** [comment]
> @dosu-bot The solution provided does not work. Also Accelarate is not part of langchain as well.
> 
> `from langchain.llms import Accelerate`
> 
> does not work.

Hey, did you find any solution to run the code in GPU? cause i have the same problem that you had
